myvlog/myvlog/urls.py
from django.urls import path, include
from django.contrib import admin
from debug_toolbar.toolbar import debug_toolbar_urls


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('vlog.urls')),
    path('users/', include('users.urls', namespace='users')),
] + debug_toolbar_urls()

myvlog/users/urls.py
from django.urls import path, reverse_lazy
from . import views

from django.contrib.auth.views import (PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordChangeDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView, 
                                       LogoutView,)


app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.Register.as_view(), name='register'),

    path('password-reset/',
         PasswordResetView.as_view(
               template_name="form_post.html",
               email_template_name="users/password_reset_email.html",
               success_url=reverse_lazy("users:password_reset_done"),
               extra_context={'title_btn': 'Отправить'},
               title="Сброс пароля"),
               name='password_reset'),

    path('password-reset/done/',
         PasswordResetDoneView.as_view(
               template_name="users/password_reset_done.html",
               title="Письмо отправлено"),
               name='password_reset_done'),

     path("password-reset/<uidb64>/<token>",
          PasswordResetConfirmView.as_view(
               template_name="form_post.html",
               success_url=reverse_lazy("users:password_reset_complete"),
               extra_context={'title_btn': 'Сменить пароль'},
               title="Придумайте новый пароль"),
               name="password_reset_confirm"),

     path("password-reset/complete/",
          PasswordResetCompleteView.as_view(
               template_name="users/password_reset_complete.html",
               title="Придумайте новый пароль"),
               name="password_reset_complete"),

     


]

myvlog/vlog/urls.py
from django.conf.urls.static import static
from django.views.decorators.cache import cache_page
from django.urls import path
from . import views
from myvlog import settings


urlpatterns = [
    path('', views.MainPage.as_view(), name='main'),

    path('account_management/',
         views.AccountManagement.as_view(),
         name='account_management'),

    path('account_management/upload_video/',
         views.UpLoadVideo.as_view(),
         name='upload_video'),

    path('account_management/create_channel/',
         views.CreateChannel.as_view(),
         name="create_channel"),

    path('profile/<str:prof_name>', views.Prof.as_view(), name="prof"),
    path('watch/<str:video_name>', views.PlayerVideo.as_view(), name="watch"),
    path('stream/<int:pk>/', views.get_streaming_video, name='stream'),

    path('comment', views.CreateComment.as_view(), name="comment"),
    path('like', views.LikeVideo.as_view(), name="like"),
    path('subscribe', views.Subscribe.as_view(), name='subscribe'),
    path('delete_video', views.DeleteVideo.as_view(), name='delete_video'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = views.page_not_found

myvlog/templates/base.html
<!DOCTYPE html>
<html lang="ru">
	<head>
		{% load static %}
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>{% block title %} {% endblock %}</title>

		<!-- Шрифты с Google Fonts -->
		<link rel="preconnect" href="https://fonts.gstatic.com" />
		<link
			href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,400;0,700;1,400&display=swap"
			rel="stylesheet"
		/>

		<!-- Стили сайта -->
		{% block style %}{% endblock %}
		<link
			rel="stylesheet"
			href='{% static "/clup_joy/css/styles_heder.css" %}'
		/>
	</head>
	<body>
		<header>
			<div class="dropdown">
				<button
					class="dropdown-toggle"
					easy-toggle="#main_menu"
					easy-class="show"
					easy-rcoe
				>
					<ion-icon name="menu-outline"></ion-icon>
				</button>
				<nav id="main_menu" class="main_menu">
					{% if user.is_authenticated %}
					<a href="/profile/{{ channel.name }}">Вы </a>
					{% else %}
					<a href="{% url 'users:login' %}">Вы </a>
					{% endif %}
					<a href="/">Главная</a>
					<a href="#">Подписки</a>
					<a href="#">История</a>
					<a href="#">Понравившиеся</a>
					<form action="{% url 'users:logout' %}" method="post">
						{% csrf_token %}
						<button class="sub_logout" type="submit">Выход из аккаунта</button>
					</form>
				</nav>
			</div>
			<div class="brend">
				<a href="/">
					<span id="span1"><b>Clip</b></span>
					<span id="span2"><b>Joy</b></span>
				</a>
			</div>

			<div class="serch">
				<input type="text" id="serch-in" class="serch-input" />
				<button type="submit" class="sub-btn">
					<ion-icon name="search-outline"></ion-icon>
				</button>
			</div>

			<div class="mychenal">
				{% if user.is_authenticated %}
				<a href="/profile/{{ user.name|default:'account_management'}}">
					<img src="{{ user.logo.url }}" alt="Вы" />
				</a>
				{% else %}
				<a href="{% url 'users:login' %}">
					<span class="login">Войти</span>
				</a>
				{% endif %}
			</div>
		</header>

		{% block content %}{% endblock %}

		<script src="https://cdn.jsdelivr.net/npm/easy-toggler@2.2.7"></script>

		<script
			type="module"
			src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"
		></script>

		<script
			nomodule
			src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"
		></script>
	</body>
</html>

myvlog/templates/form_post.html
{% extends "base.html" %}
<p></p>

{% block title %} {{title}} {% endblock title %}
<p></p>

{% block style %} {% load static %}

<link rel="stylesheet" href='{% static "clup_joy/css/login.css" %}' />
{% endblock style %}
<p></p>

{% block content %}
<div class="contain">
	<div class="login_contain">
		<span class="mainlable">{{ title }}</span>
		<div class="form_contain">
			<form action="" method="post" enctype="multipart/form-data">
				{% csrf_token %} {{ form.as_p }}
				<div id="fileName" class="file-name"></div>
				<span class="btn_sub">
					<button type="submit">{{ title_btn }}</button>
				</span>
			</form>
		</div>
	</div>
</div>

{% endblock content %}