myvlog/myvlog/urls.py
from django.urls import path, include
from django.contrib import admin
from debug_toolbar.toolbar import debug_toolbar_urls


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('vlog.urls')),
    path('users/', include('users.urls', namespace='users')),
] + debug_toolbar_urls()

myvlog/vlog/urls.py
from django.conf.urls.static import static
from django.views.decorators.cache import cache_page
from django.urls import path
from . import views
from myvlog import settings


urlpatterns = [
    path('', views.MainPage.as_view(), name='main'),

    path('account_management/',
         views.AccountManagement.as_view(),
         name='account_management'),

    path('account_management/upload_video/',
         views.UpLoadVideo.as_view(),
         name='upload_video'),

    path('account_management/create_channel/',
         views.CreateChannel.as_view(),
         name="create_channel"),

    path('profile/<str:prof_name>', views.Prof.as_view(), name="prof"),
    path('watch/<str:video_name>', views.PlayerVideo.as_view(), name="watch"),
    path('stream/<int:pk>/', views.get_streaming_video, name='stream'),

    path('comment', views.CreateComment.as_view(), name="comment"),
    path('like', views.LikeVideo.as_view(), name="like"),
    path('subscribe', views.Subscribe.as_view(), name='subscribe'),
    path('delete_video', views.DeleteVideo.as_view(), name='delete_video'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = views.page_not_found

myvlog/vlog/models.py
import uuid

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import FileExtensionValidator

def generate_unique_name():
    #Генератор уникального названия канала
    return f'user_{uuid.uuid4().hex}'

class User(AbstractUser):
    name = models.CharField(max_length=150, unique=True, default=generate_unique_name)
    logo = models.ImageField(upload_to='channel_images/', default='channel_images/AnonymUser.png')
    description = models.TextField(blank=True, null=True, max_length=1024,)
    subscribers = models.ManyToManyField("User", related_name='subscribed_users')

    class Meta:
        ordering = ['-username']

    def is_subscribed(self, other_user):
        return self.subscribers.filter(id=other_user.id).exists()

    def __str__(self):
        return self.name

 
class Video(models.Model):
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField(blank=True)
    video = models.FileField(
        upload_to='videos/videos/',
        validators=[FileExtensionValidator(allowed_extensions=['mp4'])],)
    
    photo = models.ImageField(upload_to='videos/images/')
    views = models.IntegerField(default=0)
    liked_by = models.ManyToManyField(User, related_name='liked_users')
    disliked_by = models.ManyToManyField(User, related_name='disliked_users')
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    pub_date = models.DateTimeField(auto_now_add=True)

    def reaction_checks(self, user):
        if self.liked_by.filter(pk = user.pk).exists():
            return "like"
        elif self.disliked_by.filter(pk = user.pk).exists():
            return "dislike"
        else:
            return False

    def __str__(self):
        return self.name


class Comment(models.Model):
    text = models.TextField(max_length=512)
    video = models.ForeignKey(Video, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.PROTECT)

myvlog/templates/mytube/account_management.html
{% extends "base.html" %}
<p></p>

{% block title %} {{title}} {% endblock title %}
<p></p>

{% block style %} {% load static %}

<link rel="stylesheet" href='{% static "clup_joy/css/login.css" %}' />
{% endblock style %}
<p></p>

{% block content %}
<div class="contain">
	<div class="login_contain">
		<span class="mainlable">{{ title }}</span>
		<div class="form_contain">
			<span class="btn_sub">
				<a href="{% url 'create_channel' %}">
					<button>Редактировать канал</button>
				</a>
			</span>
			<span class="btn_sub">
				<a href="{% url 'upload_video' %}">
					<button>Загрузить видео</button>
				</a>
			</span>
			<span class="btn_sub">
				<a href="{% url 'prof' prof_name=user.name %}">
					<button>Назад</button>
				</a>
			</span>
		</div>
	</div>
</div>

{% endblock content %}

myvlog/templates/mytube/channel.html
{% extends "base.html" %}
<p></p>

{% block title %} {{ title }} {% endblock title %}
<p></p>

{% block style %} {% load static %}

<link rel="stylesheet" href='{% static "clup_joy/css/styles_block.css" %}' />
<link rel="stylesheet" href='{% static "clup_joy/css/styles_channel.css" %}' />
<script src="{% static 'clup_joy/js/subscribe_form.js' %}"></script>
{% endblock style %}
<p></p>

{% block content %}
<div class="main_container">
	<div class="about">
		<div class="about_block">
			<div class="img">
				<img src="{{ author_channel.logo.url }}" alt="Вы" />
			</div>
			<div class="title">
				<h1>{{ author_channel.name }}</h1>
				<span>
					<span id="subscribers-count">
						{{ author_channel.subscribers.count }}
					</span> подписчиков
				</span>
				{% if author_channel == user %}
				<div class="account_management">
					<a href="{% url 'account_management' %}"
						>Управление видео и аккаунтом</a
					>
				</div>
				{% else %}
					{% if subscribe_status %}
					<button
						type="submit"
						class="subscribe-btn active"
						id="subscribe-btn-id"
						easy-toggle="#subscribe-btn-id"
						easy-class="active" 
						
						onclick="subscribe(`{{ author_channel.name }}`)">
					</button>
					{% else %}
					<button
						type="submit"
						class="subscribe-btn"
						id="subscribe-btn-id"
						easy-toggle="#subscribe-btn-id"
						easy-class="active"
						onclick="subscribe(`{{ author_channel.name }}`)">
					</button>
					{% endif %}
				{% endif %}
			</div>
		</div>
		{% if author_channel.description %}
		<div class="description">
			<details>
				<summary>Описание</summary>
				<span> {{author_channel.description}} </span>
			</details>
		</div>
		{% endif %}
	</div>

	<main class="main-block" id="main-block">
		<hr style="display: flex" />
		{% for video in author_channel.video_set.all %}
		<div class="container">
			<a href="{% url 'watch' video_name=video.name %}">
				<div class="image-block">
					<img src="{{ video.photo.url }}" alt="" />
				</div>

				<div class="info">
					<div class="author-img">
						<img src="{{ author_channel.logo.url }}" alt="" />
					</div>

					<div class="info-text">
						<h3>{{ video.name }}</h3>
						<span>1,2 млн | {{ video.pub_date }}</span>
					</div>
				</div>
			</a>
		</div>
		{% endfor %}
	</main>
</div>
{% endblock content %}

myvlog/templates/mytube/index.html
{% extends "base.html" %}
<p></p>

{% block title %} Clip Joy {% endblock title %}
<p></p>

{% block style %} {% load static %}
<link rel="stylesheet" href='{% static "clup_joy/css/styles_block.css" %}' />
{% endblock style %}
<p></p>

{% block content %}
{% load cache %}
<main class="main-block" id="main-block">
	{% for video in videos %}

	<div class="container">
		<a href="{% url 'watch' video_name=video.name %}">
			<div class="image-block">
				<img src="{{ video.photo.url }}" alt="" />
			</div>

			<div class="info">
				<div class="author-img">
					<img src="{{ video.author.logo.url }}" alt="" />
				</div>

				<div class="info-text">
					<h3>{{ video.name }}</h3>
					<span>1,2 млн | {{ video.pub_date }}</span>
				</div>
			</div>
		</a>
	</div>

	{% endfor %}
</main>
{% endblock content %}

myvlog/templates/mytube/video_player.html
{% extends "base.html" %}
<p></p>

{% block title %} {{ video.name }} {% endblock title %}
<p></p>

{% block style %} {% load static %}
<link rel="stylesheet" href='{% static "clup_joy/css/styles_video.css" %}' />
{% endblock style %}
<p></p>

{% block content %}
<div class="main-block">
	<div class="video-block">
		<video
              controls
              preload="auto"
          >
            <source src="{% url 'stream' video.id %}" type="video/mp4"/>
            <source src="{% url 'stream' video.id %}" type="video/webm"/>
		</video>
	</div>
	<div class="info-block">
		<div class="info-container">
			<span class="vide-name">{{ video.name }}</span>
			<div class="reacsions">
				<a class="a-profurl" href="{% url 'prof' prof_name=video.author.name %}">
					<div class="author-img">
						<img src="{{video.author.logo.url}}" alt="" />
					</div>
					<div class="name-chanel">
						<h4>{{ video.author.name }}</h4>
						<span id="subscribers-count">
							{{ video.author.subscribers.count }}
						</span>
					</div>
				</a>
				<div class="buttons">
					{% if user != video.author %}
						{% if subscribe_status %}
						<button
							type="submit"
							class="subscribe-btn active"
							id="subscribe-btn-id"
							onclick="subscribe(`{{ video.author.name }}`)">
						</button>
						{% else %}
						<button
							type="submit"
							class="subscribe-btn"
							id="subscribe-btn-id"
							onclick="subscribe(`{{ video.author.name }}`)">
						</button>
						{% endif %}
					{% else %}
						<button
							type="submit"
							id="delvideo-btn"
							onclick="delvideo()">
							Удалить видео
						</button>
					{% endif %}

					<div class="ld">
							{% if reaction == 'like' %}
							<button 
								class="like active"
								id="like"
								onclick="reactions('{{ video.name }}', 'like')">
							{% else %}
							<button
								class="like"
								id="like"
								onclick="reactions('{{ video.name }}', 'like')">
							{% endif %}
								<ion-icon name="thumbs-up-outline"></ion-icon>
								<span id="like_count">{{ video.liked_by.count }}</span> |
							</button>


							{% if reaction == 'dislike'  %}
							<button
								class="dislike active"
								id="dislike"
								onclick="reactions('{{ video.name }}', 'dislike')">
							{% else %}
							<button
								class="dislike"
								id="dislike"
								onclick="reactions('{{ video.name }}', 'dislike')">
							{% endif %}
								<ion-icon name="thumbs-down-outline"></ion-icon>
								<span id="dislike_count">{{ video.disliked_by.count }}</span>
							</button>
						</form>
					</div>
				</div>
			</div>

			{% if video.description %}
			<div class="description">
				<details>
					<summary>Описание:</summary>
					<p>{{ video.description }}</p>
				</details>
			</div>
			{% endif %}
			<div class="commentaries">
				<h2><span id="comment_count">{{ video.comment_set.count }}</span> комментариев</h2>
				<form id="comment_form">
					{% csrf_token %}
					<span class="comment-input">
						<p>
							<input type="text"
								name="text"
								placeholder="Введите свой комментарий"
								maxlength="512"
								required
								id="id_text">
						</p>
						<input type="hidden" , name="video" , value="{{ video.name }}" />
						<span class="btn_sub">
							<button type="submit">Оставить комментарий</button>
						</span>
					</span>
				</form>
				<hr />
				<ul id="comments_set">
					{% for comment in comments %}
					<li>
						<div class="comment">
							<div class="comment-author">
								<img src="{{comment.author.logo.url}}" alt="" />
							</div>
							<div class="comment-text">
								<h4 style="margin-bottom: 5px">{{ comment.author.name }}</h4>
								<p>{{ comment.text }}</p>
							</div>
						</div>
					</li>
					{% endfor %}
				</ul>
			</div>
		</div>
	</div>
</div>

<script src="{% static 'clup_joy/js/subscribe_form.js' %}"></script>
<script src="{% static 'clup_joy/js/like_form.js' %}"></script>
<script src="{% static 'clup_joy/js/comment_form.js' %}"></script>
<script src="{% static 'clup_joy/js/del_video.js' %}"></script>

<input type="hidden" id="username" value="{{ user.name }}">
<input type="hidden" id="userlogo" value="{{ user.logo.url }}">
{% endblock content %}