myvlog/myvlog/urls.py
from django.urls import path, include
from django.contrib import admin
from debug_toolbar.toolbar import debug_toolbar_urls


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('vlog.urls')),
    path('users/', include('users.urls', namespace='users')),
] + debug_toolbar_urls()

myvlog/users/urls.py
from django.urls import path, reverse_lazy
from . import views

from django.contrib.auth.views import (PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordChangeDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView, 
                                       LogoutView,)


app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.Register.as_view(), name='register'),

    path('password-reset/',
         PasswordResetView.as_view(
               template_name="form_post.html",
               email_template_name="users/password_reset_email.html",
               success_url=reverse_lazy("users:password_reset_done"),
               extra_context={'title_btn': 'Отправить'},
               title="Сброс пароля"),
               name='password_reset'),

    path('password-reset/done/',
         PasswordResetDoneView.as_view(
               template_name="users/password_reset_done.html",
               title="Письмо отправлено"),
               name='password_reset_done'),

     path("password-reset/<uidb64>/<token>",
          PasswordResetConfirmView.as_view(
               template_name="form_post.html",
               success_url=reverse_lazy("users:password_reset_complete"),
               extra_context={'title_btn': 'Сменить пароль'},
               title="Придумайте новый пароль"),
               name="password_reset_confirm"),

     path("password-reset/complete/",
          PasswordResetCompleteView.as_view(
               template_name="users/password_reset_complete.html",
               title="Придумайте новый пароль"),
               name="password_reset_complete"),

     


]

myvlog/vlog/urls.py
from django.conf.urls.static import static
from django.views.decorators.cache import cache_page
from django.urls import path
from . import views
from myvlog import settings


urlpatterns = [
    path('', views.MainPage.as_view(), name='main'),

    path('account_management/',
         views.AccountManagement.as_view(),
         name='account_management'),

    path('account_management/upload_video/',
         views.UpLoadVideo.as_view(),
         name='upload_video'),

    path('account_management/create_channel/',
         views.CreateChannel.as_view(),
         name="create_channel"),

    path('profile/<str:prof_name>', views.Prof.as_view(), name="prof"),
    path('watch/<str:video_name>', views.PlayerVideo.as_view(), name="watch"),
    path('stream/<int:pk>/', views.get_streaming_video, name='stream'),

    path('comment', views.CreateComment.as_view(), name="comment"),
    path('like', views.LikeVideo.as_view(), name="like"),
    path('subscribe', views.Subscribe.as_view(), name='subscribe'),
    path('delete_video', views.DeleteVideo.as_view(), name='delete_video'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = views.page_not_found

myvlog/users/models.py
from django.db import models

# Create your models here.

myvlog/users/forms.py
from typing import Any
from django import forms 
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import get_user_model


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='',
            widget=forms.TextInput(attrs={'placeholder': 'Логин'}))
    
    password = forms.CharField(label='', 
            widget=forms.PasswordInput(attrs={'placeholder': 'Пароль'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class RegisterUserForm(forms.ModelForm):
    username = forms.CharField(label='Логин',
        widget=forms.TextInput(attrs={'placeholder': 'Логин (используется при авторизации)'}))
    
    password = forms.CharField(label='Пароль', 
        widget=forms.PasswordInput(attrs={'placeholder': 'Пароль'}))

    password2 = forms.CharField(label='', 
        widget=forms.PasswordInput(attrs={'placeholder': "Повтор пароля"}))
    
    class Meta:
        model = get_user_model()
        fields = ['username', "email", "password", "password2"]
        labels = {
            'email': 'Ваша почта',
        }
        widgets = {
            "email": forms.TextInput(attrs={'placeholder': 'clipjoy@gmail.com'}),
        }
    
    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError("Пароли не совпадают!")
        return cd['password']
    
    
    def clean_email(self):
        email = self.cleaned_data["email"]
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("Данный E-mail уже используется")
        return email
    

myvlog/users/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login
from django.urls import reverse, reverse_lazy
from django.contrib.auth.views import LoginView
from django.views import View

from .forms import LoginUserForm, RegisterUserForm



class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Вход в аккаунт'}

class  Register(View):
    """Форма регистрации на сайте"""

    @staticmethod
    def post(request):
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)   
            user.set_password(form.cleaned_data['password'])
            user.save()
            return render(request, 'users/register_done.html')
    

    @staticmethod
    def get(request):
        form = RegisterUserForm
        data = {'title': 'Регистрация',
                'title_btn': 'Зарегистрироваться',
                'form': form}
        return render(request, 'form_post.html', data)

myvlog/templates/users/login.html
{% extends "base.html" %}
<p></p>

{% block title %} {{ title }} {% endblock title %}
<p></p>

{% block style %} {% load static %}

<link rel="stylesheet" href='{% static "clup_joy/css/login.css" %}' />
{% endblock style %}
<p></p>

{% block content %}
<div class="contain">
	<div class="login_contain">
		<span class="mainlable">Вход</span>
		<div class="form_contain">
			<form action="" method="post">
				{% csrf_token %} {{ form.as_p }}

				<a
					class="reset_password_contain"
					href="{% url 'users:password_reset' %}"
					>Забыли пароль?
				</a>

				<span class="btn_sub">
					<button type="submit">Войти</button>
				</span>
			</form>
		</div>
	</div>

	<div class="logout_contain">
		<span
			>Еще не аккаунта? <a href="/users/register">Зарегистрируйтесь</a>
		</span>
	</div>
</div>
{% endblock content %}

myvlog/templates/users/password_reset_complete.html
{% extends "base.html" %}
<p></p>

{% block title %} Пароль сменен {% endblock title %}
<p></p>

{% block style %} {% load static %}

<link rel="stylesheet" href='{% static "clup_joy/css/login.css" %}' />

{% endblock style %}
<p></p>

{% block content %}
<div class="good_register">
	<div class="good_register2">
		<h1>Пароль успешно сменен</h1>
		<span class="login_span"
			><h3>
				<a href="/users/login">Остался только войти в аккаунт</a>
			</h3></span
		>
	</div>
</div>

{% endblock content %}

myvlog/templates/users/password_reset_done.html
{% extends "base.html" %}
<p></p>

{% block title %} Восстановление пароля {% endblock title %}
<p></p>

{% block style %} {% load static %}

<link rel="stylesheet" href='{% static "clup_joy/css/login.css" %}' />

{% endblock style %}
<p></p>

{% block content %}
<div class="good_register">
	<div class="good_register2">
		<h1>Письмо отправлено</h1>
		<h3>
			На ваш почтовый ящик было отправлено письмо с инструкцией по сбросу
			пароля. Если письмо не пришло проверьте папку
			<span color="red">(СПАМ)</span>!
		</h3>
	</div>
</div>

{% endblock content %}

myvlog/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}Вы получили это письмо, потому что вы запросили сброс пароля для своей учетной записи пользователя на  {{ site_name }}.{% endblocktranslate %}

{% translate "Пожалуйста, перейдите на следующую страницу и создайте новый пароль:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Ваше имя пользователя, если вы забыли:' %} {{ user.get_username }}

{% translate "Спасибо за использование нашего сайта!" %}

{% blocktranslate %}Команда {{ site_name }} {% endblocktranslate %}

{% endautoescape %}

myvlog/templates/users/register_done.html
{% extends "base.html" %}
<p></p>

{% block title %} Регистрация {% endblock title %}
<p></p>

{% block style %} {% load static %}

<link rel="stylesheet" href='{% static "clup_joy/css/login.css" %}' />

{% endblock style %}
<p></p>

{% block content %}
<div class="good_register">
	<div class="good_register2">
		<h1>Поздравляем с успешной регистрацией</h1>
		<h3>
			Мы рады видеть вас среди наших новых пользователей!!! Теперь вы можете:
			выкладывать видео, оставлять комментарии, ставать лайки и дизлайки(если
			видео вам не понравилась). Желаем приятного пользования!!!
		</h3>
		<span class="login_span"
			><h3>
				<a href="/users/login">Остался только войти в аккаунт</a>
			</h3></span
		>
	</div>
</div>

{% endblock content %}